version: "3.9"

services:
  blacklog:
    image: andreydelay/blacklog
    build: .
    restart: on-failure
    ports:
      - '8080:8000'
    environment:
      FILE_STORAGE_SERVICE_URL: /api/v1/files
      FILE_STORAGE_SERVICE_HOST: file-storage
      POSTGRES_HOST: postgres
      POSTGRES_DB: blacklog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
      - file-storage
    networks:
      - custom

  postgres:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: blacklog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - custom

  file-storage:
    image: andreydelay/file-storage
    build: ../file-storage/
    restart: on-failure
    ports:
      - '8001'
    networks:
      - custom

networks:
  custom:
    driver: bridge
    #ipam:
      #config:
        #- subnet: 192.168.220.0/24