server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        show-sql: true
    liquibase:
      changelog: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      enabled: true
      max-file-size: 150MB
      max-request-size: 150MB
      file-size-threshold: 2048

feign:
  client:
    decodeSlash: false

feign-client:
  url:
    file-storage-service: ${FILE_STORAGE_SERVICE_HOST}:8001${FILE_STORAGE_SERVICE_URL}

logging:
  level:
    com.nipi.blacklog.feign: DEBUG
  file:
    name: logs/file-storage-feign-client.log